- .woodpecker.yml
fixes #8 
I don't see a downside in going rolling with `alpine/helm`. Saves some maintenance work in the future?
For the `chart-releaser` it might be better to stick to a fixed version?
> Update CI image versions

- woodpecker-server/templates/statefulset.yaml
As I was trying to deploy woodpecker on kubernetes today, I noticed that my pod is sitting in a pending state due to the persistentVolume not being created. After a bit of reading, I learned that k8s only provisions volumes dynamically if `storageClassName` is completely omitted from the pvc definition. 
I basically copied this code from drone's helm chart, wihch uses dynamic provisioning by default, or you can disable it by setting `storageClass: "-"`. 
I couldn't test this since I'm not sure how to test helm changes locally, but the change is pretty simple so I assume it will work. 
Let me know if there's anything wrong with it and I'll be happy to fix!
> Enable dynamic provisioning of persistentVolumes

- .woodpecker/release.yml
As we already depend on the test workflow we don't need those steps in the release workflow again
> Remove duplicated steps

- .woodpecker/release.yml
- Fixes https://ci.woodpecker-ci.org/repos/8958/pipeline/256/5
`cd` was sending the user to the home-directory `/root`, but not to the woodpecker workspace `/woodpecker/src` using `cd ..` solved the problem
- removed deprecated `--charts-repo` arg from `cr`
> Fix release

- charts/server/templates/pod-monitor.yaml
- charts/server/templates/statefulset.yaml
- charts/server/values.yaml
Enable metrics endpoint with a different port.
Add a new environment variable and expose the port.
> chore: enabled metrics with pod-monitor for statefulset

- charts/agent/values.yaml
- values.yaml
I noticed this documentation was either missing or had incorrect syntax.
> add documentation for extra volume mounts in agent

- .woodpecker/release.yml
- README.md
Publish chart to GH package registry alongside the gh-pages hosting. Supported since helm 3.8.
Advantages: 
- "Proper" chart release page
- Download count tracking
- Historic version overview
Example: https://github.com/pat-s/otf-agent-helm/pkgs/container/otf-agent-helm%2Fotf-agent
Needs:
> Publish chart to OCI registry (alongside gh-pages)

- charts/woodpecker/charts/server/templates/statefulset.yaml
When using database for persistence no volumes are required.
> fix volumeMounts if persistentVolume is not enabled

- charts/woodpecker/charts/server/unittests/statefulset/secrets.yaml
The test is still defined in another one in the same file (it was duplicated beforehand and the selector was actually buggy in the plugin).
> Fix unittest after plugin update

- charts/woodpecker/charts/agent/templates/statefulset.yaml
Fix bug in agent statefulset template that caused the whole  file to be inserted in the  and  parameters of the template.
Closes #182
> Correctly apply extraVolumes and extraVolumeMounts

- charts/woodpecker/charts/agent/templates/statefulset.yaml
- charts/woodpecker/charts/agent/unittests/statefulset/pvc.yaml
Ref #171 
@IceBear2k
I was unable to replicate your issue.
`helm template charts/woodpecker/charts/agent/ --set persistence.enabled=true` renders a valie statefulset for me and doesn't include `volumeMounts` and `volumeClaimTemplates` as shown in your screenshot. Can you verify this on your own? 
Are you setting additional options?
```yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
name: release-name-agent
labels:
helm.sh/chart: agent-0.3.0
app.kubernetes.io/name: agent
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "2.4.1"
app.kubernetes.io/managed-by: Helm
spec:
serviceName: release-name-agent
replicas: 2
selector:
matchLabels:
app.kubernetes.io/name: agent
app.kubernetes.io/instance: release-name
template:
metadata:
labels:
app.kubernetes.io/name: agent …
```
> Improve agent sts pvc tests

- release-config.ts
https://ci.woodpecker-ci.org/repos/8958/pipeline/933/4
```
Branch "next-release/main" does not exist yet, creating it.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package curl
/bin/sh: 1: curl: not found
/bin/sh: 1: helm: not found
```
> Fix release config

- Chart.lock
- charts/woodpecker/Chart.lock
- charts/woodpecker/Chart.yaml
- charts/woodpecker/charts/agent/Chart.yaml
- charts/woodpecker/charts/server/Chart.yaml
- release-config.ts
Addresses
```
Error: Chart.yaml file is missing
```
when calling `helm dependency update`.
The latter is actually of importance when updating the subchart versions to create a valid `Chart.lock`.
However, we lately didn't update the subchart versions and just bumped the umbrella chart.
There are also no public releases of the subcharts.
While for the server this is debatable, the `agent` chart is actually interesting as this one could be deployed standalone in a meaningful way.
Maybe we should maintain all of them at the same hierarchy level and rename the `woodpecker` chart to `woodpecker-stack`?
> Update subcharts and release config

- charts/woodpecker/charts/agent/Chart.yaml
- charts/woodpecker/charts/agent/templates/role.yaml
Present, the chart adds the meaningless RBAC rules for verbs `create`, `update`, `list`, and `delete` for the `pods/log` resource. While this is allowed, these permissions are meaningless, and are never checked for by Kubernetes.
While this is not an issue in of itself, within Kubernetes, a user must be granted a permission in order to create a Role or RoleBinding that grants it. In centrally-managed multi-tenant clusters, it is unlikely that these meaningless permissions will be granted by default unless the user is a cluster or namespace administrator (i.e. `*` verb granted), or specifically requested, meaning the chart is unusable by those unprivileged users in its current state.
This patch splits out just the single necessary `get` verb for `pods/log` so that unprivileged users can …
> Remove uneeded agent role rules

- release-config.ts
They are listed anyhow by default:
In addition, the (hardcoded) default including the two hearts looks somewhat unprofessional (personal opinion).
I am not 100% sure if the config option is honored though, I found it here: https://github.com/woodpecker-ci/plugin-ready-release-go/blob/7aea0c10ee3e72ea9730ec99d6af1132c46f14b4/src/utils/change.ts#L98C7-L98C26. 
@anbraten might know better.
> release-plugin: don't include contributors

- .woodpecker/release.yml
- charts/woodpecker/README.md
- charts/woodpecker/README.md.gotmpl
The idea would be to publish to both sources for a few releases and promote the older approach as deprecated.
Advantages for ghcr:
- Better visibility and "closeness" to the repo than using gh-pages
- Simpler and cleaner release code
- OCI registries are the "new" standard for helm charts
Todo:
> Publish chart to ghcr

- .woodpecker/release.yml
Currently the secret wasn't used as it is injected case-sensitive. Also not 100% sure if `secrets` is still working in `next`.
> Fix ghcr login

- CODEOWNERS
Background:
- `renovate-approve` bot doesn't work when CODEOWNER reviews are required
- `renovate-approve` bot can't be added as a CODEOWNER
- review requests for renovate dep updates in `.woodpecker` creates unneeded noise
Yes, renovate tracks some files in `charts/` but these are effectively managed by the release plugin before renovate takes action.
> Refine CODEOWNER

- .woodpecker/release.yml
The latest release accidentally pushed the tarball into the repo: https://github.com/woodpecker-ci/helm/tree/main/tmp
> fix: update tarball output dir

- .woodpecker/release.yml
fix #264 
Otherwise the README isn't prettier compliant after a release run.
> fix: run prettier after README update

- .woodpecker/release.yml
This reverts commit 39034445106186ed4dd555748c9a8c06f85eb35e.
Ref: https://github.com/woodpecker-ci/helm/issues/323
> Revert "chore(deps): update quay.io/helmpack/chart-releaser docker tag to v1.7.0 (#305)"

- charts/woodpecker/charts/server/templates/statefulset.yaml
- charts/woodpecker/charts/server/values.yaml
- charts/woodpecker/values.yaml
Woodpecker Server StatefulSet generates `livenessProbe` and `readinessProbe` with default values.
Relevant section of the generated yaml looks like:
```
livenessProbe:
httpGet:
path: /healthz
port: 8000
scheme: HTTP
timeoutSeconds: 1
periodSeconds: 10
successThreshold: 1
failureThreshold: 3
readinessProbe:
httpGet:
path: /healthz
port: 8000
scheme: HTTP
timeoutSeconds: 1
periodSeconds: 10
successThreshold: 1
failureThreshold: 3
```
Under load, I've noticed that liveness probes timed out in quick succession, which leads to the server getting restarted.
This PR adds configuration options to the template and surfaces them through server/values.yaml and values.yaml
> Add configurable prober options for woodpecker server

- charts/woodpecker/charts/agent/templates/statefulset.yaml
- charts/woodpecker/charts/server/templates/statefulset.yaml
due to missing apiVersion and kind headers argocd always detects a diff.
This commit adds the optional fields that resolve this issue.
> Add api version and kind to volume claim template
