woodpecker-ci/helm

- .woodpecker.yml
- Chart.lock
- Chart.yaml
- add `Chart.lock`
- Try fixing chart deps according to some web research
- Update WP version
Seems to work: https://ci.woodpecker-ci.org/woodpecker-ci/helm/pipeline/52/5
NB: chart version is at 0.1.1 though there is not 0.1.1 tag
> Fix release action

- .woodpecker.yml
- Chart.lock
- Chart.yaml
- README.md.gotmpl
- charts/agent/Chart.yaml
- charts/agent/values.yaml
- charts/server/Chart.yaml
- charts/server/values.yaml
- values.yaml
Related to #9
Actually, only the main `values.yaml` generates a proper `README.md`
```shell
helm-docs -t README.md.gotmpl
```
> Generate README.md with helm-docs

- Chart.lock
- Chart.yaml
- charts/agent/Chart.yaml
- charts/server/Chart.yaml
- charts/server/values.yaml
- ct.yaml
I went with 1.0.0 for the chart as well since it seems to be working fine for some time now.
> Update app version to 1.0.0

- .woodpecker/test.yml
due to https://ci.woodpecker-ci.org/repos/8958/pipeline/183/12
> no unshallow

- .woodpecker/test.yml
https://ci.woodpecker-ci.org/repos/8958/pipeline/211/12
> Fix test workflow for tags

- charts/agent/templates/deployment.yaml
- charts/agent/values.yaml
- charts/server/templates/statefulset.yaml
- charts/server/values.yaml
This PR allows configuring a custom command for the containers.
> feature: add custom command

- .woodpecker/release.yml
Run only on tag and PR. aa9bd42e349f85523dae4efeae808e5d95d5d09c ran for tag and push.
> Don't run release workflow twice

- charts/agent/values.yaml
- values.yaml
> fix woodpecker_server to work out of the box

- charts/agent/templates/deployment.yaml
- charts/agent/values.yaml
> Fix missing `image.registry` for agent

- charts/agent/README.md
- charts/agent/templates/deployment.yaml
- charts/agent/values.yaml
- values.yaml
As not needed.
~~I guess we need a label indicating "breaking".~~
-> major as this is one is understand by the `release-drafter` automatically
> Remove dind

- charts/server/templates/statefulset.yaml
> Correctly condition `volumeMounts`

- release-config.ts
> Prepend 'v' to appVersion

- charts/agent/templates/deployment.yaml
- charts/server/templates/statefulset.yaml
- release-config.ts
more beautiful then #117 / "appVersion: version"
PS: Why are the images are not tagges the semver way?
https://docs.inedo.com/docs/proget-docker-semantic-versioning
> fix: image with v version prefix

- README.md
- charts/woodpecker/charts/agent/README.md
- charts/woodpecker/charts/server/README.md
So we don't have to update them manually. See https://shields.io/badges/dynamic-yaml-badge.
> Use dynamic badges

- CHANGELOG.md
- charts/woodpecker/README.md
- charts/woodpecker/README.md.gotmpl
> Remove references to OCI Chart

- README.md
- release-config.ts
> Small fixes

- charts/woodpecker/charts/agent/templates/deployment.yaml
- charts/woodpecker/charts/agent/unittests/deployment/initContainers.yaml
- charts/woodpecker/charts/agent/values.yaml
- charts/woodpecker/charts/server/templates/statefulset.yaml
- charts/woodpecker/charts/server/unittests/statefulset/initContainers.yaml
- charts/woodpecker/charts/server/values.yaml
- charts/woodpecker/values.yaml
fix #110 
+ accidental prettier formatting
> add `initContainers` and tests

- charts/woodpecker/README.md
> Add documentation for secret generation/handling

- charts/woodpecker/README.md
- charts/woodpecker/values.yaml
https://github.com/woodpecker-ci/helm/pull/163#discussion_r1518257856
> Set pv size to 1Gb

- .woodpecker/release.yml
> Fix wp syntax in workflow file

- release-config.ts
Since the underlying image is now using debian instead of alpine.
> Adjust "before prepare" hook

- README.md
As previously worded, it seemed to me to suggest you shouldn't use the `woodpecker` chart!
> Clarification in README.md

- charts/woodpecker/charts/agent/templates/role.yaml
Added Secret create/delete RBAC needed for https://github.com/woodpecker-ci/woodpecker/pull/4092
> RBAC for Registry Secrets

- renovate.json
> Remove custom package rules and config

- charts/woodpecker/Chart.lock
- charts/woodpecker/Chart.yaml
- charts/woodpecker/README.md
- charts/woodpecker/README.md.gotmpl
- charts/woodpecker/charts/agent/Chart.yaml
- charts/woodpecker/charts/agent/README.md
- charts/woodpecker/charts/agent/README.md.gotmpl
- charts/woodpecker/charts/server/Chart.yaml
- charts/woodpecker/charts/server/README.md
- charts/woodpecker/charts/server/README.md.gotmpl
> bump chart versions and add migration notes

- charts/woodpecker/charts/agent/values.yaml
- charts/woodpecker/charts/server/values.yaml
After the change with the default user and group. I got an error about a read only database. After setting the fsGroup everything worked again.
> Also set the default file system group Security Context

- charts/woodpecker/README.md
Fixes: https://github.com/woodpecker-ci/helm/issues/314
> Fix oci helm install command

- charts/woodpecker/README.md
- charts/woodpecker/README.md.gotmpl
> Fix path of oci repo
